cask_args appdir: "~/Applications"

cask "claude"
cask "dash"
cask "docker-desktop"
cask "figma"
cask "ghostty"
cask "imageoptim"
cask "keka"
cask "monitorcontrol"
cask "notion"
cask "rectangle"
cask "sketch"
cask "slack"
cask "thebrowsercompany-dia"
cask "via"
